# Generated by Django 4.2.5 on 2023-10-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flushing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flushingservice',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
