# Generated by Django 4.2.5 on 2023-10-04 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flushing', '0002_flushingservice_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flushinggallery',
            name='time_update',
        ),
        migrations.AlterField(
            model_name='flushinggallery',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flushing.typeflushingservice', verbose_name='Тип промывки'),
        ),
    ]
