# Generated by Django 4.2.5 on 2023-10-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flushing', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='client_name',
            new_name='name',
        ),
    ]
