# Generated by Django 4.2.5 on 2023-10-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flushing', '0006_topicarticle_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['time_create'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='topicarticle',
            options={'ordering': ['name'], 'verbose_name': 'Тема статьи', 'verbose_name_plural': 'Темы статей'},
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles_images/', verbose_name='Изображение'),
        ),
    ]
